const fs = require('fs').promises;
const paths = require('../lib/paths');

/**
 * Writes out the flag files generated by concentrate
 *
 * This is needed so SiteHtmlHeadEntrySetDisplayer will use the compiled
 * LESS paths when rendering the page on the server.
 */
module.exports = async function writeFlags() {
  const ts = Math.floor(new Date().getTime() / 1000);
  await fs.writeFile(paths.compiledFlag, ts);
};
